### ISSUE TITLE
React group project: day 0

### ISSUE THREAD

**Issue by fernandorpm** [fernandorpm/space-travelers-hub#25]
# React group project: day 0

## Link to the Project
- https://github.com/fernandorpm/space-travelers-hub

## Group members
- Gabriel Rendon
- Fernando Marques

## Total Members
- 2

## Day 0 Requirements
- Join a Zoom call with your team. Only one person needs to copy the board on behalf of the entire team but everybody should help during the call.
- Create an empty repository for your group project.
- Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] React Group Project](https://github.com/microverseinc/curriculum-react-redux/projects/1) board.
- Open the GitHub project (Kanban board) in your team repo.
- Make sure that in the card titles you can see categories:  `Setup`, `Fetch data`, `Lists render`, `Actions`, `Conditional components`, `Filters`.
- Make sure that each card starts with `[Xpt]` - that number indicates the number of `points` that shows how complex the task is. **1 point = 1 hour of work**.
- _If your group includes two people - remove all cards with `Team3` in the title._
- Each of the team members should assign themselves to the cards from all categories (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.
- [Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue).
    - In its description, paste a link to your GitHub project.
    - Add a note telling the reviewer how many people there are in your team.
- Use the issue link to ask for a review. A Code Reviewer will leave you feedback in the issue's comment.
    - As it is your first time using a GitHub project and Kanban board, we need to double-check your setup to avoid problems while working on your project.

**Comment by Emmyn5600** [comment]
## STATUS: CHANGES REQUESTED :recycle:

Hi, @fernandorpm  and @gabrielyea 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
Changes required :writing_hand: 

Original changes requested:
 ` For a team with 2 people - Number of cards in Backlog should be equal to 17 not 14 as you did. Kindly, make sure that we have 17.`
       
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by Temmarie** [comment]
Hello  @fernandorpm and @gabrielyea   :wave: 

_This is an additional review as a result of the second opinion request._

You complained about the reviewer only counting 14 cards instead of 17, this must have been an oversight on their part. As this was the only reason why your project was not approved, kindly request for a review after making the other requested change and it will be approved immediately by the next code reviewer.  
Keep rocking :rocket:!

**Comment by Davidosky007** [comment]
## Hi @fernandorpm @gabrielyea 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
* Kindly provide a link to your project in the description the link would enable me to review your project as it is a requirement for this project 🙏 
![image](https://user-images.githubusercontent.com/52497246/131377481-5471d37a-0628-4be3-bcc5-ceb801a263ea.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Davidosky007** [comment]
## Hi @fernandorpm @gabrielyea 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 
## [OPTIONAL]
* I suggest you replace the link in the description with https://github.com/fernandorpm/space-travelers-hub/projects/2  as this leads directly to your project 👍 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
